---
abstract: 'Send warnings to Growl'
author:
  - 'kpee <kpee.cpanx@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Growl
provides:
  Carp::Growl:
    file: lib/Carp/Growl.pm
    version: v0.0.6
requires:
  Growl::Any: 0
  Test::More: 0
  version: 0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: v0.0.6
